name: TheCommandBook
main: pro.homiecraft.TheCommandBook
version: 1.0
author: GudfareN
website: homiecraft.pro

commands:
   setspawn:
      description: Set world spawn location to your current location.
      permission: tcb.Setspawn
      usage: /setspawn'
   spawn:
      description: Teleports you to the current world spawn.
      permission: tcb.spawn
      usage: /spawn
   sethome:
      description: Set your current location as your home.
      permission: tcb.Sethome
      usage: /sethome
   home:
      description: Teleports you to your home location.
      permission: tcb.home
      usage: /home
   tp:
      description: Teleports you to the specified player.
      permission: tcb.tp
      usage: /tp playerName
   tpl:
      description: Teleports you to a players last location. Before leaving the server.
      permission: tcb.tpl
      usage: /tpl playerName
   tphere:
      description: Teleports a specified player to you.
      permission: tcb.tphere
      usage: /tphere playerName
   setwarp:
      description: Sets a warp at your location.
      permission: tcb.setwarp
      usage: /setwarp warpName
   warp:
      description: Warps to a specified warp.
      permission: tcb.warp
      usage: /warp warpName
   delwarp:
      description: Delete a specified warp.
      permission: tcb.delwarp
      usage: /delwarp warpName
   warps:
      description: List all warps
      permission: tcb.warps
      usage: /warps
   mute:
      description: Mute a specified player.
      permission: tcb.mute
      usage: /mute playerName
   kick:
      description: Kick a specified player.
      permission: tcb.kick
      usage: /kick playerName <reason>
   ban:
      description: Ban a specified player.
      permission: tcb.ban
      usage: /ban playerName <reason>
   unban:
      description: Unban a specified player.
      permission: tcb.unban
      usage: /unban playerName
   msg:
      description: Msg a specified player.
      permission: tcb.msg
      usage: /msg playerName <message>
   time:
      description: Change day night
      permission: tcb.time
      usage: /time day|night
   weather:
      description: Change the weather
      permission: tcb.weather
      usage: /weather sun|rain
   gm:
      description: Change gamemode for you or another player
      permission: tcb.gm
      usage: /gm <playerName>
   god:
      description: God a player
      permission: tcb.god
      usage: /god <playerName>
   played:
      description: Lookup playtime for a player
      permission: tcb.played
      usage: /played <playerName>