name: TheCommandBook
main: pro.homiecraft.TheCommandBook
version: 1.0
author: GudfareN
website: homiecraft.pro

commands:
   setspawn:
      description: Set world spawn location to your current location.
      permission: tcb.Setspawn
      usage: /setspawn'
   spawn:
      description: Teleports you to the current world spawn.
      permission: tcb.spawn
      usage: /spawn
   sethome:
      description: Set your current location as your home.
      permission: tcb.Sethome
      usage: /sethome
   home:
      description: Teleports you to your home location.
      permission: tcb.home
      usage: /home
   tp:
      description: Teleports you to the specified player.
      permission: tcb.tp
      usage: /tp playerName
   tphere:
      description: Teleports a specified player to you.
      permission: tcb.tphere
      usage: /tphere playerName
   setwarp:
      description: Sets a warp at your location.
      permission: tcb.setwarp
      usage: /setwarp warpName
   warp:
      description: Warps to a specified warp.
      permission: tcb.warp
      usage: /warp warpName